apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: techtrends
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.imagePullPolicy }} 
        name: techtrends
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe }}
             port: 3111
        readinessProbe:
           httpGet:
             path: {{ .Values.readinessProbe }}
             port: 3111
        resources:
{{ toYaml .Values.resources | indent 12 }}